backend:
  replicas: 0
chunksCache:
  enabled: false
deploymentMode: SingleBinary
gateway:
  image:
    tag: 1.29-alpine
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  image:
    tag: 3.6.4
  limits_config:
    allow_structured_metadata: false
    reject_old_samples: false
  schemaConfig:
    configs:
    - from: '2024-01-01'
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v13
      store: boltdb-shipper
  storage:
    type: filesystem
  storageConfig:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks
memcached:
  image:
    tag: 1.6.39-alpine
memcachedExporter:
  image:
    tag: v0.15.4
nodeSelector:
  node:
    platform: amd64
  node.platform: amd64
read:
  replicas: 0
sidecar:
  image:
    tag: 1.30.9
singleBinary:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
write:
  replicas: 0
