alertmanager:
  enabled: false
grafana:
  enabled: false
kubeStateMetrics:
  image:
    tag: v2.18.0
nodeSelector:
  node:
    platform: amd64
  node.platform: amd64
prometheus:
  prometheusSpec:
    image:
      tag: v3.9.1
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    retention: 15d
prometheusOperator:
  image:
    tag: v0.88.1
