apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.1
    meta.helm.sh/release-name: traefik-crd
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: apiportals.hub.traefik.io
spec:
  conversion:
    strategy: None
  group: hub.traefik.io
  names:
    kind: APIPortal
    listKind: APIPortalList
    plural: apiportals
    singular: apiportal
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: APIPortal defines a developer portal for accessing the documentation
          of APIs.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object.

              Servers should convert recognized schemas to the latest internal value,
              and

              may reject unrecognized values.

              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents.

              Servers may infer this from the endpoint the client submits requests
              to.

              Cannot be updated.

              In CamelCase.

              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: The desired behavior of this APIPortal.
            properties:
              auth:
                description: Auth references the APIPortalAuth resource for authentication
                  configuration.
                properties:
                  name:
                    description: Name is the name of the APIPortalAuth resource.
                    maxLength: 253
                    type: string
                required:
                - name
                type: object
              description:
                description: Description of the APIPortal.
                type: string
              title:
                description: Title is the public facing name of the APIPortal.
                type: string
              trustedUrls:
                description: TrustedURLs are the urls that are trusted by the OAuth
                  2.0 authorization server.
                items:
                  type: string
                maxItems: 1
                minItems: 1
                type: array
                x-kubernetes-validations:
                - message: must be a valid URLs
                  rule: self.all(x, isURL(x))
              ui:
                description: UI holds the UI customization options.
                properties:
                  logoUrl:
                    description: LogoURL is the public URL of the logo.
                    type: string
                type: object
            required:
            - trustedUrls
            type: object
        type: object
    served: true
    storage: true
