apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - accesscontrolpolicies.hub.traefik.io.yaml
  - addons.k3s.cattle.io.yaml
  - aiservices.hub.traefik.io.yaml
  - alertmanagerconfigs.monitoring.coreos.com.yaml
  - alertmanagers.monitoring.coreos.com.yaml
  - apiauths.hub.traefik.io.yaml
  - apibundles.hub.traefik.io.yaml
  - apicatalogitems.hub.traefik.io.yaml
  - apiplans.hub.traefik.io.yaml
  - apiportalauths.hub.traefik.io.yaml
  - apiportals.hub.traefik.io.yaml
  - apiratelimits.hub.traefik.io.yaml
  - apis.hub.traefik.io.yaml
  - apiversions.hub.traefik.io.yaml
  - etcdsnapshotfiles.k3s.cattle.io.yaml
  - gatewayclasses.gateway.networking.k8s.io.yaml
  - gateways.gateway.networking.k8s.io.yaml
  - grpcroutes.gateway.networking.k8s.io.yaml
  - helmchartconfigs.helm.cattle.io.yaml
  - helmcharts.helm.cattle.io.yaml
  - httproutes.gateway.networking.k8s.io.yaml
  - ingressroutes.traefik.io.yaml
  - ingressroutetcps.traefik.io.yaml
  - ingressrouteudps.traefik.io.yaml
  - managedapplications.hub.traefik.io.yaml
  - managedsubscriptions.hub.traefik.io.yaml
  - middlewares.traefik.io.yaml
  - middlewaretcps.traefik.io.yaml
  - podlogs.monitoring.grafana.com.yaml
  - podmonitors.monitoring.coreos.com.yaml
  - probes.monitoring.coreos.com.yaml
  - prometheusagents.monitoring.coreos.com.yaml
  - prometheuses.monitoring.coreos.com.yaml
  - prometheusrules.monitoring.coreos.com.yaml
  - referencegrants.gateway.networking.k8s.io.yaml
  - scrapeconfigs.monitoring.coreos.com.yaml
  - serverstransports.traefik.io.yaml
  - serverstransporttcps.traefik.io.yaml
  - servicemonitors.monitoring.coreos.com.yaml
  - thanosrulers.monitoring.coreos.com.yaml
  - tlsoptions.traefik.io.yaml
  - tlsstores.traefik.io.yaml
  - traefikservices.traefik.io.yaml
