apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cms.namespace.yaml
  - default.namespace.yaml
  - ingress-nginx.namespace.yaml
  - kube-node-lease.namespace.yaml
  - kube-public.namespace.yaml
  - kube-system.namespace.yaml
  - monitoring.namespace.yaml
  - observability.namespace.yaml
  - recipelab.namespace.yaml
