apiVersion: batch/v1
kind: Job
metadata:
  name: ingress-ingress-nginx-admission-create
  namespace: ingress-nginx
$patch: delete
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ingress-ingress-nginx-admission-patch
  namespace: ingress-nginx
$patch: delete
