apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cms
resources:
  - apps/mariadb.helmrelease.yaml
  - apps/redis.helmrelease.yaml
  - apps/wordpress.helmrelease.yaml
  - backups/bind-wp-backups.yaml
  - backups/cms-backups-pvc.yaml
  - backups/cms-backups-wp-pvc.yaml
  - backups/list-db-backups.yaml
  - backups/list-wp-backups.yaml
  - backups/mariadb-backup-cronjob.yaml
  - backups/mariadb-restore-test-cronjob.yaml
  - backups/wordpress-backup-cronjob.yaml
  - backups/wp-cronjob.yaml
  - network/wordpress.ingress.yaml
configMapGenerator:
  - name: cms-mariadb-values
    files:
      - values.yaml=values/mariadb.values.yaml
  - name: cms-redis-values
    files:
      - values.yaml=values/redis.values.yaml
  - name: cms-wordpress-values
    files:
      - values.yaml=values/wordpress.values.yaml
generatorOptions:
  disableNameSuffixHash: true
