apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/proxy-body-size":"64m"},"name":"wordpress","namespace":"cms"},"spec":{"ingressClassName":"nginx","rules":[{"host":"cms.thealgoera.com","http":{"paths":[{"backend":{"service":{"name":"wordpress","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}

      '
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
  creationTimestamp: '2026-02-06T05:15:21Z'
  generation: 1
  name: wordpress
  namespace: cms
  resourceVersion: '98951'
  uid: f55674cb-9656-4807-8f4c-db5c85d3f315
spec:
  ingressClassName: nginx
  rules:
  - host: cms.thealgoera.com
    http:
      paths:
      - backend:
          service:
            name: wordpress
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 10.43.45.99
