apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - admin.clusterrole.yaml
  - alloy-log-reader.clusterrole.yaml
  - alloy-log-reader.clusterrolebinding.yaml
  - alloy-read-logs.clusterrole.yaml
  - alloy-read-logs.clusterrolebinding.yaml
  - alloy-read-pods-and-logs.clusterrole.yaml
  - alloy-read-pods-and-logs.clusterrolebinding.yaml
  - alloy.clusterrole.yaml
  - alloy.clusterrolebinding.yaml
  - cluster-admin.clusterrole.yaml
  - cluster-admin.clusterrolebinding.yaml
  - clustercidrs-node.clusterrole.yaml
  - clustercidrs-node.clusterrolebinding.yaml
  - edit.clusterrole.yaml
  - grafana-clusterrole.clusterrole.yaml
  - grafana-clusterrolebinding.clusterrolebinding.yaml
  - helm-kube-system-traefik-crd.clusterrolebinding.yaml
  - helm-kube-system-traefik.clusterrolebinding.yaml
  - k3s-cloud-controller-manager-auth-delegator.clusterrolebinding.yaml
  - k3s-cloud-controller-manager.clusterrole.yaml
  - k3s-cloud-controller-manager.clusterrolebinding.yaml
  - kube-apiserver-kubelet-admin.clusterrolebinding.yaml
  - local-path-provisioner-bind.clusterrolebinding.yaml
  - local-path-provisioner-role.clusterrole.yaml
  - loki-clusterrole.clusterrole.yaml
  - loki-clusterrolebinding.clusterrolebinding.yaml
  - metrics-server:system:auth-delegator.clusterrolebinding.yaml
  - prometheus-kube-prometheus-operator.clusterrole.yaml
  - prometheus-kube-prometheus-operator.clusterrolebinding.yaml
  - prometheus-kube-prometheus-prometheus.clusterrole.yaml
  - prometheus-kube-prometheus-prometheus.clusterrolebinding.yaml
  - prometheus-kube-state-metrics.clusterrole.yaml
  - prometheus-kube-state-metrics.clusterrolebinding.yaml
  - system:aggregate-to-admin.clusterrole.yaml
  - system:aggregate-to-edit.clusterrole.yaml
  - system:aggregate-to-view.clusterrole.yaml
  - system:aggregated-metrics-reader.clusterrole.yaml
  - system:auth-delegator.clusterrole.yaml
  - system:basic-user.clusterrole.yaml
  - system:basic-user.clusterrolebinding.yaml
  - system:certificates.k8s.io:certificatesigningrequests:nodeclient.clusterrole.yaml
  - system:certificates.k8s.io:certificatesigningrequests:selfnodeclient.clusterrole.yaml
  - system:certificates.k8s.io:kube-apiserver-client-approver.clusterrole.yaml
  - system:certificates.k8s.io:kube-apiserver-client-kubelet-approver.clusterrole.yaml
  - system:certificates.k8s.io:kubelet-serving-approver.clusterrole.yaml
  - system:certificates.k8s.io:legacy-unknown-approver.clusterrole.yaml
  - system:controller:attachdetach-controller.clusterrole.yaml
  - system:controller:attachdetach-controller.clusterrolebinding.yaml
  - system:controller:certificate-controller.clusterrole.yaml
  - system:controller:certificate-controller.clusterrolebinding.yaml
  - system:controller:clusterrole-aggregation-controller.clusterrole.yaml
  - system:controller:clusterrole-aggregation-controller.clusterrolebinding.yaml
  - system:controller:cronjob-controller.clusterrole.yaml
  - system:controller:cronjob-controller.clusterrolebinding.yaml
  - system:controller:daemon-set-controller.clusterrole.yaml
  - system:controller:daemon-set-controller.clusterrolebinding.yaml
  - system:controller:deployment-controller.clusterrole.yaml
  - system:controller:deployment-controller.clusterrolebinding.yaml
  - system:controller:disruption-controller.clusterrole.yaml
  - system:controller:disruption-controller.clusterrolebinding.yaml
  - system:controller:endpoint-controller.clusterrole.yaml
  - system:controller:endpoint-controller.clusterrolebinding.yaml
  - system:controller:endpointslice-controller.clusterrole.yaml
  - system:controller:endpointslice-controller.clusterrolebinding.yaml
  - system:controller:endpointslicemirroring-controller.clusterrole.yaml
  - system:controller:endpointslicemirroring-controller.clusterrolebinding.yaml
  - system:controller:ephemeral-volume-controller.clusterrole.yaml
  - system:controller:ephemeral-volume-controller.clusterrolebinding.yaml
  - system:controller:expand-controller.clusterrole.yaml
  - system:controller:expand-controller.clusterrolebinding.yaml
  - system:controller:generic-garbage-collector.clusterrole.yaml
  - system:controller:generic-garbage-collector.clusterrolebinding.yaml
  - system:controller:horizontal-pod-autoscaler.clusterrole.yaml
  - system:controller:horizontal-pod-autoscaler.clusterrolebinding.yaml
  - system:controller:job-controller.clusterrole.yaml
  - system:controller:job-controller.clusterrolebinding.yaml
  - system:controller:legacy-service-account-token-cleaner.clusterrole.yaml
  - system:controller:legacy-service-account-token-cleaner.clusterrolebinding.yaml
  - system:controller:namespace-controller.clusterrole.yaml
  - system:controller:namespace-controller.clusterrolebinding.yaml
  - system:controller:node-controller.clusterrole.yaml
  - system:controller:node-controller.clusterrolebinding.yaml
  - system:controller:persistent-volume-binder.clusterrole.yaml
  - system:controller:persistent-volume-binder.clusterrolebinding.yaml
  - system:controller:pod-garbage-collector.clusterrole.yaml
  - system:controller:pod-garbage-collector.clusterrolebinding.yaml
  - system:controller:pv-protection-controller.clusterrole.yaml
  - system:controller:pv-protection-controller.clusterrolebinding.yaml
  - system:controller:pvc-protection-controller.clusterrole.yaml
  - system:controller:pvc-protection-controller.clusterrolebinding.yaml
  - system:controller:replicaset-controller.clusterrole.yaml
  - system:controller:replicaset-controller.clusterrolebinding.yaml
  - system:controller:replication-controller.clusterrole.yaml
  - system:controller:replication-controller.clusterrolebinding.yaml
  - system:controller:resource-claim-controller.clusterrole.yaml
  - system:controller:resource-claim-controller.clusterrolebinding.yaml
  - system:controller:resourcequota-controller.clusterrole.yaml
  - system:controller:resourcequota-controller.clusterrolebinding.yaml
  - system:controller:root-ca-cert-publisher.clusterrole.yaml
  - system:controller:root-ca-cert-publisher.clusterrolebinding.yaml
  - system:controller:route-controller.clusterrole.yaml
  - system:controller:route-controller.clusterrolebinding.yaml
  - system:controller:selinux-warning-controller.clusterrole.yaml
  - system:controller:selinux-warning-controller.clusterrolebinding.yaml
  - system:controller:service-account-controller.clusterrole.yaml
  - system:controller:service-account-controller.clusterrolebinding.yaml
  - system:controller:service-cidrs-controller.clusterrole.yaml
  - system:controller:service-cidrs-controller.clusterrolebinding.yaml
  - system:controller:service-controller.clusterrole.yaml
  - system:controller:service-controller.clusterrolebinding.yaml
  - system:controller:statefulset-controller.clusterrole.yaml
  - system:controller:statefulset-controller.clusterrolebinding.yaml
  - system:controller:ttl-after-finished-controller.clusterrole.yaml
  - system:controller:ttl-after-finished-controller.clusterrolebinding.yaml
  - system:controller:ttl-controller.clusterrole.yaml
  - system:controller:ttl-controller.clusterrolebinding.yaml
  - system:controller:validatingadmissionpolicy-status-controller.clusterrole.yaml
  - system:controller:validatingadmissionpolicy-status-controller.clusterrolebinding.yaml
  - system:controller:volumeattributesclass-protection-controller.clusterrole.yaml
  - system:controller:volumeattributesclass-protection-controller.clusterrolebinding.yaml
  - system:coredns.clusterrole.yaml
  - system:coredns.clusterrolebinding.yaml
  - system:discovery.clusterrole.yaml
  - system:discovery.clusterrolebinding.yaml
  - system:heapster.clusterrole.yaml
  - system:k3s-controller.clusterrole.yaml
  - system:k3s-controller.clusterrolebinding.yaml
  - system:kube-aggregator.clusterrole.yaml
  - system:kube-controller-manager.clusterrole.yaml
  - system:kube-controller-manager.clusterrolebinding.yaml
  - system:kube-dns.clusterrole.yaml
  - system:kube-dns.clusterrolebinding.yaml
  - system:kube-scheduler.clusterrole.yaml
  - system:kube-scheduler.clusterrolebinding.yaml
  - system:kubelet-api-admin.clusterrole.yaml
  - system:metrics-server.clusterrole.yaml
  - system:metrics-server.clusterrolebinding.yaml
  - system:monitoring.clusterrole.yaml
  - system:monitoring.clusterrolebinding.yaml
  - system:node-bootstrapper.clusterrole.yaml
  - system:node-problem-detector.clusterrole.yaml
  - system:node-proxier.clusterrole.yaml
  - system:node-proxier.clusterrolebinding.yaml
  - system:node.clusterrole.yaml
  - system:node.clusterrolebinding.yaml
  - system:persistent-volume-provisioner.clusterrole.yaml
  - system:public-info-viewer.clusterrole.yaml
  - system:public-info-viewer.clusterrolebinding.yaml
  - system:service-account-issuer-discovery.clusterrole.yaml
  - system:service-account-issuer-discovery.clusterrolebinding.yaml
  - system:volume-scheduler.clusterrole.yaml
  - system:volume-scheduler.clusterrolebinding.yaml
  - view.clusterrole.yaml
