auth:
  database: wordpress
  existingSecret: mariadb
  password: <<REDACTED>>
  rootPassword: <<REDACTED>>
  username: dustin
image:
  tag: 12.1.2
metrics:
  image:
    tag: 0.16.0
nodeSelector:
  node:
    platform: amd64
  node.platform: amd64
primary:
  configuration: '[mysqld]

    skip-name-resolve

    bind-address=0.0.0.0

    port=3306

    socket=/opt/bitnami/mariadb/tmp/mysql.sock

    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

    innodb_buffer_pool_size=256M

    max_connections=200

    slow_query_log=1

    long_query_time=1

    log_queries_not_using_indexes=0


    [client]

    port=3306

    socket=/opt/bitnami/mariadb/tmp/mysql.sock'
  nodeSelector:
    node-role.algoera: mariadb
    node.platform: amd64
  persistence:
    enabled: true
    size: 20Gi
resources:
  limits:
    cpu: 750m
    memory: 768Mi
  requests:
    cpu: 500m
    memory: 512Mi
