apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
  - prometheus-kube-prometheus-admission.mutatingwebhookconfiguration.yaml
  - prometheus-kube-prometheus-admission.validatingwebhookconfiguration.yaml
