apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-ingress-nginx-admission.validatingwebhookconfiguration.yaml
  - prometheus-kube-prometheus-admission.mutatingwebhookconfiguration.yaml
  - prometheus-kube-prometheus-admission.validatingwebhookconfiguration.yaml
