apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/prometheus-operated.service.yaml
  - apps/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0.configmap.yaml
  - network/grafana.ingress.yaml
