apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: IngressClass
  metadata:
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.14.3
      helm.sh/chart: ingress-nginx-4.14.3
    name: nginx
  spec:
    controller: k8s.io/ingress-nginx
- apiVersion: networking.k8s.io/v1
  kind: IngressClass
  metadata:
    labels:
      app.kubernetes.io/instance: traefik-kube-system
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: traefik
      helm.sh/chart: traefik-37.1.1_up37.1.0
    name: traefik
  spec:
    controller: traefik.io/ingress-controller
