apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/alloy-config.configmap.yaml
  - apps/alloy.daemonset.yaml
  - rbac/alloy-log-reader.serviceaccount.yaml
  - rbac/alloy.serviceaccount.yaml
